In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Input
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [
    "the glass of milk", 
    "the glass of juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "understand the meaning of words",
    "your videos are good"
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [5]:
one_hot_represent = [one_hot(words, voc_size) for words in sent]
one_hot_represent

[[1582, 2594, 160, 4327],
 [1582, 2594, 160, 5345],
 [1582, 1038, 160, 6496],
 [9218, 4587, 9199, 5011, 1887],
 [9218, 4587, 9199, 5011, 2536],
 [700, 1582, 3787, 160, 12],
 [3513, 1858, 7571, 5011]]

In [6]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_represent, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1582 2594  160 4327]
 [   0    0    0    0 1582 2594  160 5345]
 [   0    0    0    0 1582 1038  160 6496]
 [   0    0    0 9218 4587 9199 5011 1887]
 [   0    0    0 9218 4587 9199 5011 2536]
 [   0    0    0  700 1582 3787  160   12]
 [   0    0    0    0 3513 1858 7571 5011]]


In [7]:
dim = 10

In [8]:
model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(input_dim=voc_size, output_dim=dim))
model.compile(optimizer='adam', loss='mse')

In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step


array([[[ 0.02360834, -0.04983382, -0.00354839, -0.01526107,
          0.03247612, -0.00897037, -0.00360214, -0.00363477,
          0.04740225, -0.00284361],
        [ 0.02360834, -0.04983382, -0.00354839, -0.01526107,
          0.03247612, -0.00897037, -0.00360214, -0.00363477,
          0.04740225, -0.00284361],
        [ 0.02360834, -0.04983382, -0.00354839, -0.01526107,
          0.03247612, -0.00897037, -0.00360214, -0.00363477,
          0.04740225, -0.00284361],
        [ 0.02360834, -0.04983382, -0.00354839, -0.01526107,
          0.03247612, -0.00897037, -0.00360214, -0.00363477,
          0.04740225, -0.00284361],
        [-0.04632968,  0.02456411,  0.01245501, -0.03792182,
          0.03848011, -0.00633355,  0.01174624, -0.04442504,
         -0.03593532,  0.02906075],
        [-0.04344887,  0.04487599, -0.03282778, -0.01887486,
         -0.03309625, -0.01207111, -0.03049176,  0.04566897,
         -0.01702112, -0.00663091],
        [-0.027702  , -0.02422075,  0.03602797, -0.0

In [11]:
embedded_docs[0]

array([   0,    0,    0,    0, 1582, 2594,  160, 4327])

In [12]:
# model.predict(np.expand_dims(embedded_docs[0], axis=0))
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step


array([[[ 0.02360834, -0.04983382, -0.00354839, -0.01526107,
          0.03247612, -0.00897037, -0.00360214, -0.00363477,
          0.04740225, -0.00284361],
        [ 0.02360834, -0.04983382, -0.00354839, -0.01526107,
          0.03247612, -0.00897037, -0.00360214, -0.00363477,
          0.04740225, -0.00284361],
        [ 0.02360834, -0.04983382, -0.00354839, -0.01526107,
          0.03247612, -0.00897037, -0.00360214, -0.00363477,
          0.04740225, -0.00284361],
        [ 0.02360834, -0.04983382, -0.00354839, -0.01526107,
          0.03247612, -0.00897037, -0.00360214, -0.00363477,
          0.04740225, -0.00284361],
        [-0.04632968,  0.02456411,  0.01245501, -0.03792182,
          0.03848011, -0.00633355,  0.01174624, -0.04442504,
         -0.03593532,  0.02906075],
        [-0.04344887,  0.04487599, -0.03282778, -0.01887486,
         -0.03309625, -0.01207111, -0.03049176,  0.04566897,
         -0.01702112, -0.00663091],
        [-0.027702  , -0.02422075,  0.03602797, -0.0

In [13]:
embedded_docs[1]

array([   0,    0,    0,    0, 1582, 2594,  160, 5345])

In [14]:
model.predict(embedded_docs[[1]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step


array([[[ 0.02360834, -0.04983382, -0.00354839, -0.01526107,
          0.03247612, -0.00897037, -0.00360214, -0.00363477,
          0.04740225, -0.00284361],
        [ 0.02360834, -0.04983382, -0.00354839, -0.01526107,
          0.03247612, -0.00897037, -0.00360214, -0.00363477,
          0.04740225, -0.00284361],
        [ 0.02360834, -0.04983382, -0.00354839, -0.01526107,
          0.03247612, -0.00897037, -0.00360214, -0.00363477,
          0.04740225, -0.00284361],
        [ 0.02360834, -0.04983382, -0.00354839, -0.01526107,
          0.03247612, -0.00897037, -0.00360214, -0.00363477,
          0.04740225, -0.00284361],
        [-0.04632968,  0.02456411,  0.01245501, -0.03792182,
          0.03848011, -0.00633355,  0.01174624, -0.04442504,
         -0.03593532,  0.02906075],
        [-0.04344887,  0.04487599, -0.03282778, -0.01887486,
         -0.03309625, -0.01207111, -0.03049176,  0.04566897,
         -0.01702112, -0.00663091],
        [-0.027702  , -0.02422075,  0.03602797, -0.0